export interface CandidacyCard {
    idNum: number;
    yearCode: string;
    divisionCode: string;
    stage: string;
    programCode: string;
    termCode: string;
    bacYear: string;
    highSchool: string;
    highSchoolDiploma: string;
    highSchoolDistinction: string;
    hsOrgTypeAd: string;
    gpa: number;
    totalApCredits: number;
    totalInstCredits: number;
    clOrgTypeAd: string | null;
    clGpa: number | null;
    clTotalApCredits: number | null;
    clTotalInstCredits: number | null;
    schoolType: string | null;
    udef1a1: string;
    act: string | null;
    gat: string | null;
    gre: string | null;
    sat: string | null;
    satRc: string | null;
    satWc: string | null;
    tef: string | null;
    toepp: string | null;
    birthDate: string;
    citizenOf: string;
    city: string;
    country: string;
    addressLine1: string;
    birthName: string;
    firstName: string;
    lastName: string;
    emailAddress: string;
    gender: string;
    mobile: string;
    fatherAddress: string | null;
    motherAddress: string | null;
    fatherPhone: string | null;
    motherPhone: string | null;
    fatherOccupation: string | null;
    motherOccupation: string | null;
    appFeeDate: string;
  }
// export interface CandidacyCard {
//   code : number;
//   idNum: number;
//   YR_CDE: string;
//   DIV_CDE: string;
//   STAGE: string;
//   PROG_CDE: string;
//   TRM_CDE: string;
//   BAC_YEAR: string;
//   HIGH_SCHOOL: string;
//   HIGH_SCHOOL_DIPLOMA: string;
//   HIGH_SCHOOL_DISTINCTION: string;
//   HS_ORG_TYPE_AD: string;
//   GPA: number;
//   TOTAL_AP_CREDITS: number;
//   TOTAL_INST_CREDITS: number;
//   CL_ORG_TYPE_AD: string | null;
//   CL_GPA: number | null;
//   CL_TOTAL_AP_CREDITS: number | null;
//   CL_TOTAL_INST_CREDITS: number | null;
//   SCHOOL_TYPE: string | null;
//   UDEF_1A_1: string;
//   ACT: string | null;
//   GAT: string | null;
//   GRE: string | null;
//   SAT: string | null;
//   SATRC: string | null;
//   SATWC: string | null;
//   TEF: string | null;
//   TOEPP: string | null;
//   BIRTH_DTE: string;
//   CITIZEN_OF: string;
//   CITY: string;
//   COUNTRY: string;
//   ADDR_LINE_1: string;
//   BIRTH_NAME: string;
//   FIRST_NAME: string;
//   LAST_NAME: string;
//   EMAIL_ADDRESS: string;
//   GENDER: string;
//   MOBILE: string;
//   FATHER_ADDRESS: string | null;
//   MOTHER_ADDRESS: string | null;
//   FATHER_PHONE: string | null;
//   MOTHER_PHONE: string | null;
//   FATHER_OCCUPATION: string | null;
//   MOTHER_OCCUPATION: string | null;
//   APP_FEE_DTE: string;
// }
